### ISSUE TITLE
sector (german Kreissektor) seems not to work

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#10]
In my visualisation sector doesn't work. I try to visualise a pump with a combination (from botton to top) of a polygon (green triangle in the right half of the circle), green sector (a green semicircle should be in the left half of the circle, but is transparent),  ellipse (black circle around the green fields) and  polyline (black line in the right half of the circle, surrounding the green triangle) (see picture below, below the pump is a green line for the pipe), everything works properly with exception of sector. It looks like this:
![Screenshot_20201228_183130](https://user-images.githubusercontent.com/3670326/103232552-07576c00-493b-11eb-8109-11375810393a.png)
The original in codesys looks like this:
![Screenshot_20201228_213329](https://user-images.githubusercontent.com/3670326/103247528-81054f00-4967-11eb-9be6-ecf4015c338d.png)

Any ideas?

**Comment by tnentwig** [comment]
Okay, I see the problem. The IDE allows to manipulate the piechart also with the corner positions. I thought this is only possible with start and end angle. I will fix it.

**Comment by tnentwig** [comment]
Should be fixed now.

**Comment by triessner** [comment]
It is better, but not yet perfect. I have two pumps in my visu. One in horizontal orientation and one in vertical. In the horizontal the sector is in the wrong (right) half:
![Screenshot_20201230_000214](https://user-images.githubusercontent.com/3670326/103319841-84660c80-4a33-11eb-9086-f245affd97b7.png)
In the vertical, the angles are a bit wrong, it should be exactly 180 degrees, but it is a little less (there should be no white stripes between the sector in the lower half and the triangle in the top):
![Screenshot_20201230_000154](https://user-images.githubusercontent.com/3670326/103319861-9e9fea80-4a33-11eb-9ed9-3ce78b09dca0.png)
But it is also possible, that the original is a bit less than 180° and the java visu shows it not really exact so that the mistake is not visible.

**Comment by tnentwig** [comment]
There was a problem with the calculation of the sign of the angles. Should be now really be fixed in 1.0.13-2.
There are no polylines in the vertical symbol of pump? Is that intentional? I will work on the other bugs after my final exam on 6. january.  Thanks for your comments!

**Comment by triessner** [comment]
Now it works. I think the problems with the vertical pump are problems in my visu, that I didn't notice before (the missing polyline around the triangle is definitely an error in the visu, the white stripe, I'm not quite sure yet).
Thanks a lot for your great work :-))
I wish you good luck in your final exams
