### ISSUE TITLE
background colour

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#13]
In my visualisation I have set no background colour. In the java version, the background is white, in this javascript version the background is light grey. To show text, I use rectangles and the background of these rectangles is white. In the original the text-rectangles integrated seamlessly in the background. In the javascript version a white rectangle hovers above the grey background which looks a bit disturbing.
![Screenshot_20201229_113219](https://user-images.githubusercontent.com/3670326/103277539-94490680-49c9-11eb-9be9-8d849c74c6f8.png)

**Comment by triessner** [comment]
Normally I'm using firefox at linux. But for some reason I looked at the javascript visu with chrome (also linux) and with firefox at a windows machine. In both cases the background colour is white :-/. Maybe it is a firefox-linux problem then?

**Comment by Ekristoffe** [comment]
interesting, does it only appears on firefox with linux ? what version of firefox are you using ?

**Comment by triessner** [comment]
I'm using Firefox 78.6.0esr (64-Bit) on an openSuSE leap 15.1 notebook

**Comment by Ekristoffe** [comment]
Could you check something ?
On the machine which have the problem, could you do a right click on the wrongly displayed element and select "inspect" then copy paste the code from the <div> to the </div>
Same thing on a normal working machine on the same element.
I would like to see what is the difference.

unfortunately all my machines under linux are headless...

**Comment by triessner** [comment]
I'm not quite sure whether I got you right. The problem is, that the background-colour of the visualisation itself is grey in firefox, not the background colour of any element. 
Nevertheless I tried to find a corresponding \<dev\> element, it is the surrounding \<div\> element of the whole visu. In linux-firefox:
`<div style="display: block; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 781px; height: 576px; transform-origin: 0px 0px 0px;
    transform: scale(1.12998);"> ....... lots of <div> ... </div> for the elements of the visu </div>`
in linux-chrome:
`<div style="display: block; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 781px; height: 576px; transform-origin: 0px 0px; transform: scale(1.57712);">....... lots of <div> ... </div> for the elements of the visu </div>`
on windows-firefox:
`<div style="display: block; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 781px; height: 576px; transform-origin: 0px 0px 0px; transform: scale(1.05546);">....... lots of <div> ... </div> for the elements of the visu </div>`

**Comment by Ekristoffe** [comment]
Hooo it is the whole page background...
Yes I haven’t enforced the white background by default but it can be easily done.
I will see to force a white background by default if none are set.

**Comment by triessner** [comment]
Still doesn't work. But I assume, there is a problem with the webvisu.html. The changelog says, that the body-tag should look like `<body style="background-color:white">` but it still is just `<body>`. For some reason, the change didn't find its way to the 1.0.13-3 release. If I change the webvisu.html manually, it works.

**Comment by Ekristoffe** [comment]
indeed we need to make a 1.0.13-4 release or go to 1.0.14 directly ...
let me see if i can do it (ps for this one you will also need to update the ,html file.

**Comment by tnentwig** [comment]
This is now included in the new release.

**Comment by Ekristoffe** [comment]
thanks

**Comment by triessner** [comment]
Works now as expected in (compressed) pre-release  1.0.14-beta
