### ISSUE TITLE
variables are not working (NaN) when webvisu.js ist stored on sd-card

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#14]
Due to very limited storage on a 750-880 controller (1,8 MB) I put the webvisu.js on the sd-card (S:/) and corrected the path in the webvisu.html `<script src="s:/webvisu.js"></script>`. The visu itself is displayed ok, but in every place, where I use numbers from the plc (actual temperatures, fluid levels, ...), just "NaN" is shown. 
Is there a way to store webvisu.js on the sd-card, or is it impossible?

**Comment by Ekristoffe** [comment]
Normally you should use the option to transfers all the PLC folder to the SD card (it should be an option on the web based management).
I don't have a 880 plc to test it at the moment ...
Could you try to see if the java based visu work ?

**Comment by triessner** [comment]
That's difficult, because the only controller with a sd-card is at a customer-site of us, and he is still using the java-visu (as far as I know). I have to contact our customer to agree with him on this test.
I will give a feedback, as soon, as I have the allowance from the customer.

**Comment by tnentwig** [comment]
I think you get a cross-origin error on the cyclic variable fetch. This would be visible as hint in the console or the network tab in the developer tools (F11). You can request the file with the given absolute path (Im confused that its possible to access the local file system this way) but the request to the codesys webserver will go to another uri. 
So without the complete transfer to the sd card like mentioned by Chris, it won't work. A solution without the usage of a sd-card would be a zipping of the js file (~200kB) in the future.

**Comment by triessner** [comment]
Zipping the js file is possible without any changes? The browser is able to unzip it automatically and I can do it myself? That would really help.
Maybe, you could provide the zipped js directly in future than, if it doesn't have any other disadvantages.

**Comment by tnentwig** [comment]
Hi, it would be quit easy to offer the static compressed file. But the server has to send a Content-Encoding: gzip in the header of the response. This isn't the case at the current server configuration. I know how to mange this for the lighttpd server of wago linux PFCs. But not on nucleus controller like 750-880. 
Unfortunately I do not have much time in the next two weeks to find a solution.

**Comment by Ekristoffe** [comment]
In that case we may use a js loader in the webvisu.html
I may look at it.

**Comment by tnentwig** [comment]
I think a good option is to use JSXCompressor. I tried successfully to compress and include the bundle in the WebVisu.html via python script. I get a size of 320kB for the bundel + 15kB for JSXCompressor. Works like a charm.
I will write a webpack plugin that will do this for us automatically on build time if you do't have another idea.

**Comment by Ekristoffe** [comment]
I had the idea to embeeded some JavaScript to get the gzip file, uncompress it and run it directly inside the html but I haven't got the time to test it.

**Comment by tnentwig** [comment]
Would be also great. With a optimized config file (like in the branch) I get a bundle size of 420 kB and 111 kB compressed (deflate). 
We get a all over size with loader of under 200 kB then. I hope this would be approbiate for older controller.

**Comment by triessner** [comment]
That sounds really good. The java file is about 367 kB. So if there is less than 200 kB free on the controller, it would always be possible to delete the webvisu.jar file. Only disadvantage in this scenario is, that codesys transfers the webvisu.jar with every program update, if it is not on the controller. So there is some juggling neccessary to deal with limited space (delete, webvisu.js, program update, delete webvisu.jar, transfer webvisu.js), but it is possible at least

**Comment by tnentwig** [comment]
The bundle size can be reduced to ~90 kB (with a few changes based on the Minimize-Bundle-Size branch). The loader of the compressed WebVisuApp is included in the new webvisu.html, so the two files in the release have to be transferred. I have deployed a beta release 1.0.14-beta. On the first side I haven't noticed a bug except the non automatic scaling of the window. Do you get a better compressing factor Chris?

**Comment by Ekristoffe** [comment]
wow that's nice
no mine where not that good (only ~300kb)
