### ISSUE TITLE
mouse pointer doesn't change when hovering over a clickable item

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#16]
When I move my mouse pointer over a clickable item, it doesn't change its shape. In the original visu in codesys, the mouse pointer changes from a simple pointer to a hand-pointer with index-finger when I move over a clickable item and to a small text cursor, when I move it over an editable item (text, number). Thus the visu is much more intuitive to use.

**Comment by Ekristoffe** [comment]
I see how to solve this.
I will do a PR when it's solved.

**Comment by Ekristoffe** [comment]
Could you test with this version:
https://github.com/Ekristoffe/WebVisu/tree/Dev/dist
The cursor should be a pointer on items with a user access.
I haven't done the small text cursor yet.

**Comment by triessner** [comment]
It works pretty well. I'd rather prefer the pointer over all items with user access (as it is now), the cursor in the java visu is very tiny and not good to see.

**Comment by Ekristoffe** [comment]
I will made another one with the right Text pointer just to see which one is more relevant and if the Text pointer to clearly visible.
Edit: dev repo updated.
