### ISSUE TITLE
Dynamic Text support

### ISSUE THREAD

**Issue by Ekristoffe** [tnentwig/WebVisu#4]
Hello,
Is there any plan to support the Dynamic text system of CoDeSys 2 ?
This is useful when you have a same program made for more than 1 language or when you need a solution for UTF (UTF-8 or UTF-16) support in CoDeSys 2.

**Comment by tnentwig** [comment]
Yes, I have planned to integrate the missing features listed in the readme within the next weeks. 
I want to implement the table and chart first. The dynamic text support would follow then. Hope it's okay.

I did't know that's not possible to use UTF charset in a monolanguage project.

**Comment by Ekristoffe** [comment]
No problem
Just at the moment if there is a text with dynamic text enable the system crash.
I think a check is missing somewhere.
(or a try catch).

**Comment by tnentwig** [comment]
Ok, I will check this within the next weeks.

**Comment by Ekristoffe** [comment]
I have found the reason.
I will patch it to show the %<tag> instead or having a crash.

**Comment by tnentwig** [comment]
Ok, interesting. I couldn't find a reason why the whole app crashes. As I understand it due to the CoDeSys manual, the usage of dynamic text with a XML-Description file will only need a text in the form of "%<something>". But I haven't created a project with xml language change yet.

**Comment by tnentwig** [comment]
Ah okay, got it. The dynamic text is placed as variable and not as placeholder. I thought it would be a placeholder. Thanks for adding your patch.
