### ISSUE TITLE
Polylines draw triangles in the angles

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#9]
Hi tnentwig,
thanks a lot for your great work. This is really a good tool to handle the vanishing java support of the old wago- visualisation.
I have a medium complex visualisation with lots of poly-lines. It seams, that for every angle in the poly-line, there is drawn a white triangle, that overlaps the other elements (see picture below).
Is there any chance, that you can fix this issue? I would gladly help you with testing

![Screenshot_20201222_101321](https://user-images.githubusercontent.com/3670326/102874427-bb8c5a80-4442-11eb-94ee-1d8bb2b8a189.png)

**Comment by Ekristoffe** [comment]
Hello triessner.
I am updating a fork of this repo. I will look in your problem. ~~Could you send the export of the visu so I can try it ?~~
I will try to solve it ASAP.

**Comment by Ekristoffe** [comment]
I see the problem, 
I also found the solution.
Could you please try those files :
https://github.com/Ekristoffe/WebVisu/tree/Dev/dist

**Comment by tnentwig** [comment]
Hi Thilo, Hi Chris,
should be fixed in the relase just uploaded. Polylines and Beziers have an fill attribute in the XMLs although there is no option for this in the IDE.

**Comment by triessner** [comment]
Hi Chris and Tristan,

thanks a lot for your quick solution, it solved my issue :-)
